[package]
name = "aoc2023"
authors = ["Ashlin Eldridge"]
description = "Advent of Code 2023"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.10", features = ["cargo", "derive"] }
regex = "1.10.2"
